# Generated by Django 5.1.15 on 2026-03-25 23:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0001_initial"),
        ("organizations", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="is_starred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to="workspaces.workspace",
            ),
        ),
        migrations.CreateModel(
            name="MediaAssetVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_number", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="media_library/versions/%Y/%m/")),
                ("thumbnail", models.ImageField(blank=True, default="", upload_to="media_library/thumbs/%Y/%m/")),
                ("change_description", models.CharField(blank=True, default="", max_length=500)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="media_library.mediaasset",
                    ),
                ),
            ],
            options={
                "db_table": "media_library_asset_version",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="media_library.mediaassetversion",
            ),
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_folders",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="media_library.mediafolder",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_folders",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "media_library_folder",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="media_library.mediafolder",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["organization", "workspace", "media_type", "created_at"], name="media_libra_organiz_c19a62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["organization", "workspace", "is_starred"], name="media_libra_organiz_a5bdf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["folder"], name="media_libra_folder__6e721f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="mediaassetversion",
            unique_together={("media_asset", "version_number")},
        ),
        migrations.AddConstraint(
            model_name="mediafolder",
            constraint=models.UniqueConstraint(
                fields=("workspace", "parent_folder", "name"), name="unique_folder_name_per_parent"
            ),
        ),
    ]
